# permissions for end users to edit nutanixclustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nutanixclustertemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-nutanix
    app.kubernetes.io/part-of: cluster-api-provider-nutanix
    app.kubernetes.io/managed-by: kustomize
  name: nutanixclustertemplate-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - nutanixclustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - nutanixclustertemplates/status
  verbs:
  - get
